name: Coding Standards Fixes & Check

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run PHPCBF
          uses: johnregan3/wpcs-phpcbf-action@develop
        - name: WP Core check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: true
            standard: 'WordPress-Core'

