name: Send to S3

on:
  push:
    branches:
      - trunk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run WPCS
        uses: 10up/wpcs-action@stable
        with:
          enable_warnings: true
          standard: 'WordPress-Core'
      - name: Create Test Files
        run: |
          mkdir dist
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy Single GA PHP File
        with:
          command: cp
          source: ./github-actions.php
          destination: s3://ithemes.ga.test/dist/github-actions.php
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
      - name: Verify File
        run: |
          echo "Verify file"
      - uses: keithweaver/aws-s3-github-action@v1.0.0 # Verifies the recursive flag
        name: Copy Folder
        with:
          command: cp
          source: ./dist/
          destination: s3://ithemes.ga.test/dist/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --recursive
      - name: Verify Folder
        run: |
          echo "Verify folder"
