name: Flywheel SSH Deploy GA Plugin
on:
  push:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy GA Plugin to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GH_ACTION_SSH_DEPLOY_KEY_PRIVATE }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        SOURCE: "dist/"
        EXCLUDE: "/dist/"
        TARGET: "/www/wp-content/plugins/"
