name: Coding Standards Fixes & Check

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run PHPCBF
          uses: uses: ge-tracker/phpcbf-action@v1
        - name: GET PHPCBF info
          run: phpcbf -i
        - name: WP Core check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: true
            standard: 'WordPress-Core'

