name: Coding Standards Fixes & Check

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: WP Core check
          uses: johnregan3/wpcs-phpcbf-action@develop
          with:
            enable_warnings: true
            standard: 'WordPress-Core'
