name: Flywheel SSH Deploy GA Plugin
on:
  push:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy GA Plugin to Server
      uses: easingthemes/ssh-deploy@v3.0.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/plugins/github-actions
